// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "src/infra/db/schema.prisma",
  migrations: {
    path: "src/infra/db/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
  typedSql: {
    path: "src/infra/db/sql",
  },
});
